version: '2.2'

services:
  loki:
    image: grafana/loki:master
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-loki
      - promtail-loki
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:master
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - promtail-loki
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/app.cfg
    networks:
      - monitor
      - grafana-prometheus
    command: >-
      --config.file=/app.cfg/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles

  grafana:
    depends_on:
      - loki
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: test
      GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
    volumes:
      - ./grafana:/app.cfg
    networks:
      - monitor
      - grafana-loki
      - grafana-prometheus

networks:
  monitor:
  nginx_proxy_manager_default:
    external: true
  promtail-loki:
    internal: true
  grafana-loki:
    internal: true
  grafana-prometheus:
    internal: true
